### ISSUE TITLE
Make IPSec optional

### ISSUE THREAD

**Issue by tlnd** [openvnf/cgw#10]
At present, the IPSec part of the CGW is mandatory -- opposed to the other functions, there is no `ipsec.enabled`. However, there are use cases where IPSec is not required, however, the remaining functionality of the CGW should still be utilized. For instance, to setup a GRE tunnel with BGP over a trusted network, I still want to utilize the CGW to have VXLAN controller, BGP metrics, Ping metrics export, etc.
So IPSec termination should become and optional part of the CGW.

**Comment by grundrauschen** [comment]
As this feature was added in commit 12b1ad7fcea69f965e95eaa1ae84cb031bf52e37 and therefore arrived starting from version 0.7.0, this issue will be closed
