### ISSUE TITLE
Missing parameters in default values.yaml

### ISSUE THREAD

**Issue by tlnd** [openvnf/cgw#13]
Running `helm install . --dry-run --debug` yields:

```
Error: render error in "cgw/templates/strongswan-ipsec-privatekeys.yaml": template: cgw/templates/strongswan-ipsec-privatekeys.yaml:1:40: executing "cgw/templates/strongswan-ipsec-privatekeys.yaml" at <.Values.ipsec.certs....>: can't evaluate field privateKeys in type interface {}
```

Hence, obviously some default parameters are missing in the `values.yaml`

**Comment by grundrauschen** [comment]
Thank you for stating the error.
There was default directory missing for testing the values.

I changed the defaults in commit d7d61cefa6e5d5d4945b3c502c8367a1ca71c5f3
