### ISSUE TITLE
Support packet capture

### ISSUE THREAD

**Issue by tlnd** [openvnf/cgw#17]
The CGW should optionally be able to capture packets according to defined filters. For this purpose, the [travelping/pcap](https://hub.docker.com/r/travelping/pcap/) docker image should be utilized.

**Comment by tlnd** [comment]
@grundrauschen @KilianDargel This should not be a big issue, maybe one of you can add this the next days. It should be included in v1.0.0.

**Comment by grundrauschen** [comment]
pcap support was added with commit 1995150e71d79564f863364837832910d4466760.

Please go ahead and verify if the current implementation is working.

**Comment by KilianDargel** [comment]
Pcap support has been tested for the (newest) release  `travelping/pcap:1.1.0` (https://github.com/travelping/docker-pcap/releases/tag/v1.1.0). Currently these capute filters + options are supported: 
```
IFACE
FILTER
MAXFILESIZE
MAXFILENUM
DURATION
FILENAME
FORMAT```

**Comment by grundrauschen** [comment]
As Kilian has tested the support, I will close this ticket.
