### ISSUE TITLE
Allow to update BIRD config at runtime

### ISSUE THREAD

**Issue by tlnd** [openvnf/cgw#38]
At present, in case of an update of the bird configuration, the CGW pod is re-created. However, it should be possible to change routing configuration at runtime without pod restart.

Kubernetes will update the config in the pod if the ConfigMap is updated. A mechanism is needed to trigger a re-configuration in case of config update: run a `configure check` and apply the config if valid. If the config is invalid, the pod should indicate that e.g. via health state - otherwise a situation may appear in which a invalid config is applied, as bird can not be re-configured, it will remain running in the old configuration until it is restarted - then it fails to come up. Hence, a invalid config should become quite visible when applied.

**Comment by hudymi** [comment]
I think the issue can be closed, as requirements are fulfilled.
