### ISSUE TITLE
Upgrade apiVersion off Deployments

### ISSUE THREAD

**Issue by tlnd** [openvnf/cgw#40]
Starting with Kubernetes v1.16 `Deployment`, `StatefulSet`, and `DaemonSet`  are no longer available in API version `extensions/v1beta1`, as they are available in `apps/v1` since v1.9: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

The templates need to be updated to consider this and support k8s 1.16.

**Comment by mgumz** [comment]
Look at #41

**Comment by grundrauschen** [comment]
As the MR was merged, this issue is closed starting from version 1.5.0
